# Generated by Django 3.2.5 on 2021-07-27 12:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_ordertabel_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertabel',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 27, 12, 44, 32, 962376)),
        ),
    ]
