# Generated by Django 3.2.5 on 2021-07-27 12:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_alter_ordertabel_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertabel',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 27, 12, 49, 48, 926116, tzinfo=utc)),
        ),
    ]
