# Generated by Django 3.2.5 on 2021-07-28 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0008_cartdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordertabel',
            name='cartitem',
        ),
    ]
