# Generated by Django 3.2.5 on 2021-07-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0009_remove_ordertabel_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdetail',
            name='expecteddate',
            field=models.DateTimeField(null=True),
        ),
    ]
